---
title: "SMART HARVEST"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: 
      version: 4
      bootswatch: minty

---

```{css, echo=FALSE}
footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: white;
  color: gray;
  text-align: center;
}
```

<footer>
  For further questions, comments and feedback please reach ozan.sonmez@bayer.com.
</footer>


```{r, echo = FALSE, warning=F, message=F}
# Get the libraries auto-installed ---------------------------------------------
source("/repos/Smart_Harvest/Modules/Dashboard/Packages.R")

# Get the Relavent Scripts for the downstream analysis ------------------------
source("/repos/Smart_Harvest/Modules/Model/Model.R")
source("/repos/Smart_Harvest/Modules/Model/rank.R")
source("/repos/Smart_Harvest/Modules/Metrics/metric.R")
source("/repos/Smart_Harvest/Modules/Metrics/precision.R")
source("/repos/Smart_Harvest/Modules/Metrics/ndcg.R")
source("/repos/Smart_Harvest/Modules/Metrics/jaccard_similarity.R")
source("/repos/Smart_Harvest/Modules/Metrics/spearman.R")
source("/repos/Smart_Harvest/Modules/Metrics/kendall.R")
source("/repos/Smart_Harvest/Modules/Metrics/marginal_rank_change.R")
source("/repos/Smart_Harvest/Modules/Metrics/genetic_gain.R")
source("/repos/Smart_Harvest/Modules/Metrics/genetic_correlation.R")
source("/repos/Smart_Harvest/Modules/Metrics/heritability.R")

# Read in the data file: -----------------------------------------------------
df_raw <- read.csv("/mnt/Data/Pepper_Zeb_Digital_Pheno_Data.csv")

# Define Other Inputs --------------------------------------------------------
chosen_traits = c("FQUAL", "FRMHAH", "NETWT")
rank_signs = c(1, 1, -1) # Rank works in an increasing order, hence for traits where large values are desired, sign of rank should be -
names(rank_signs) = chosen_traits

df_initial <- df_raw %>%
  filter(OBSRVTN_REF_CD %in% chosen_traits) %>%
  mutate_at('TRAIT_VALUE', as.numeric)
```


DATA DESCRIPTION
=======================================================================
 
Inputs {.sidebar data-width=300}
-----------------------------------------------------------------------
 
The Traits of Interests are:

```{r, echo = FALSE, warning=F, message=F}
df_initial %>%
  group_by(OBSRVTN_REF_CD) %>%
  summarise(Description = unique(FTS_OBSERVATION)) %>%
  rename(Trait = OBSRVTN_REF_CD) %>%
  kbl() %>%
  kable_paper("hover", full_width = F)

```
 

Row 
-------------------------------------


### CROP

```{r, echo = FALSE, warning=F, message=F}
crop <- unique(df_initial$CROP)
  valueBox(
    caption = "CROP",
    value = crop,
    icon = "fa-sharp fa-solid fa-seedling",
    color = "primary"
  )
```

### FIELDS

```{r, echo = FALSE, warning=F, message=F}
fields <- paste(unique(df_initial$FIELD_NAME), collapse = ",")

  valueBox(
    caption = "FIELD NAME",
    value = fields,
    icon = "fa-solid fa-location-pin-lock",
    color = "primary"
  )
```

### GROWSEASON

```{r, echo = FALSE, warning=F, message=F}
seasons <- paste(unique(df_initial$GROWSEASON), collapse = ",")
  valueBox(
    caption = "GROWSEASON",
    value = seasons,
    icon = "fa-solid fa-cloud-showers-heavy",
    color = "primary"
  )
```

### Pedigrees

```{r, echo = FALSE, warning=F, message=F}
N_ped <- n_distinct(df_initial$PEDIGREE_NAME)
  valueBox(
    caption = "# of unique Pedigrees",
    value = N_ped,
    icon = "fa-solid fa-dna",
    color = "primary"
  )
```

### Harvests

```{r, echo = FALSE, warning=F, message=F}
N_harvest <- n_distinct(df_initial$REPETITION)
  valueBox(
    caption = "Number of Harvests",
    value = N_harvest,
    icon = "fa-solid fa-chart-line",
    color = "primary"
  )
```

### Experimental Stage

```{r, echo = FALSE, warning=F, message=F}
ex_stage <- paste(unique(df_initial$EXPER_STAGE_REF_ID), collapse = ",")
  valueBox(
    caption = "Experimental Stages",
    value = ex_stage,
    icon = "fa-solid fa-flask",
    color = "primary"
  )
```

Row  {.tabset .tabset-fade .tabset-pills}
-------------------------------------

### Violin PLots

```{r, echo = FALSE, warning=F, message=F}
p <- ggplot(df_initial, aes(x = factor(REPETITION), y = TRAIT_VALUE)) +
  geom_violin(scale = "width", fill = "skyblue", trim = TRUE) +  # Plot vertical density plot
  geom_jitter(width = 0.2, size = 1, alpha = 0.5) + # Add jittered data points
  facet_wrap(~OBSRVTN_REF_CD, scales = "free_y", ncol = 2) +  # Create a separate facet for each trait
  labs(title = "Density of Trait Values over Repetitions", x = "Repetition", y = "Trait Value") +
  theme_minimal() 

# Convert the ggplot to a plotly object
ggplotly(p)

```

### Density Plots

```{r, echo = FALSE, warning=F, message=F, fig.height=9, fig.width=12}
# Create a ggplot
ggplot(df_initial, aes(x = TRAIT_VALUE, y = as.factor(REPETITION), fill = as.factor(REPETITION))) +
  ggridges::geom_density_ridges(scale = 3, rel_min_height = 0.01, alpha = 0.3) +
  facet_wrap(~OBSRVTN_REF_CD, scales = "free", nrow = 2) +
  theme_minimal() +
  labs(title = "Density of Trait Values over Repetitions", x = "Trait Value", y = "Repetition") +
  theme(legend.position = "none")
```

### Marginal Trajectories

```{r, echo = FALSE, warning=F, message=F}
# Calculate the mean trait value for each repetition and trait
mean_trait <- df_initial %>%
  group_by(REPETITION, OBSRVTN_REF_CD) %>%
  summarise(Mean_TRAIT_VALUE = mean(TRAIT_VALUE, na.rm = TRUE))

# Create a ggplot
p <- ggplot(df_initial, aes(x = REPETITION, y = TRAIT_VALUE)) +
  geom_line(aes(group = PLOT_BID), color = "gray") +  # Plot individual trajectories
  geom_line(data = mean_trait, aes(y = Mean_TRAIT_VALUE), color = "red", size = 1) +  # Plot mean trait trajectory
  facet_wrap(~OBSRVTN_REF_CD, scales = "free") +  # Create a separate facet for each trait
  labs(title = "Trajectory for Traits", x = "Repetition", y = "Trait Value") +
  theme_minimal()

# Convert the ggplot to a plotly object
ggplotly(p)
```


### Cumulative Trajectories

```{r, echo = FALSE, warning=F, message=F}
# Calculate the cumulative trait value for each repetition, individual, and trait
df <- df_initial %>%
  arrange(REPETITION) %>%
  group_by(PLOT_BID, OBSRVTN_REF_CD) %>%
  mutate(Cumulative_TRAIT_VALUE = cumsum(TRAIT_VALUE))

# Calculate the mean cumulative trait value for each repetition and trait
mean_trait <- df %>%
  group_by(REPETITION, OBSRVTN_REF_CD) %>%
  summarise(Mean_Cumulative_TRAIT_VALUE = mean(Cumulative_TRAIT_VALUE, na.rm = TRUE))

# Create a ggplot
p <- ggplot(df, aes(x = REPETITION, y = Cumulative_TRAIT_VALUE)) +
  geom_line(aes(group = PLOT_BID), color = "gray") +  # Plot individual trajectories
  geom_line(data = mean_trait, aes(y = Mean_Cumulative_TRAIT_VALUE), color = "red", size = 1) +  # Plot mean trait trajectory
  facet_wrap(~OBSRVTN_REF_CD, scales = "free") +  # Create a separate facet for each trait
  labs(title = "Cumulative Trajectory for Traits", x = "Repetition", y = "Cumulative Trait Value") +
  theme_minimal()

# Convert the ggplot to a plotly object
ggplotly(p)
```



